<template>
  <div>
    <div class="row mb-4">
      <div class="col-lg-4">
        <Select
          v-model="typeSelect"
          :options="typeList"
          @input="resetSectionSelect()"
        />
      </div>
    </div>

    <Tabs
      :list="sectionList"
      v-model="sectionSelect"
      class="mb-4"
    />

    <template v-if="typeSelect && sectionSelect">
      <Form
        :items="fieldsList"
        @success="changeSection()"
      />
    </template>
  </div>
</template>

<script>
import Select from '@/components/Select.vue';
import Tabs from '@/components/Tabs.vue';
import Form from '@/components/Form.vue';

export default {
  name: 'OrderAdd',
  components: {
    Select,
    Tabs,
    Form,
  },
  data() {
    return {
      typeSelect: '',
      sectionSelect: 'Заявитель',
      dataList: [
        {
          type: 'Физическое лицо',
          sections: [
            {
              name: 'Заявитель',
              fields: [
                {
                  name: 'typeUser',
                  placeholder: 'Тип заявителя',
                  required: true,
                  type: 'text',
                  value: '',
                  mask: '',
                },
                {
                  name: 'surname',
                  placeholder: 'Фамилия',
                  required: true,
                  type: 'text',
                  value: '',
                  mask: '',
                },
                {
                  name: 'name',
                  placeholder: 'Имя',
                  required: true,
                  type: 'text',
                  value: '',
                  mask: '',
                },
                {
                  name: 'middleName',
                  placeholder: 'Отчество',
                  required: false,
                  type: 'text',
                  value: '',
                  mask: '',
                },
                {
                  name: 'snils',
                  placeholder: 'СНИЛС',
                  required: false,
                  type: 'text',
                  value: '',
                  mask: '',
                },
                {
                  name: 'passport',
                  placeholder: 'Паспорт',
                  required: false,
                  type: 'text',
                  value: '',
                  mask: '',
                },
                {
                  name: 'series',
                  placeholder: 'Серия',
                  required: false,
                  type: 'text',
                  value: '',
                  mask: '',
                },
                {
                  name: 'number',
                  placeholder: 'Номер',
                  required: false,
                  type: 'text',
                  value: '',
                  mask: '',
                },
                {
                  name: 'issued',
                  placeholder: 'Выдан',
                  required: false,
                  type: 'text',
                  value: '',
                  mask: '',
                },
                {
                  name: 'dateIssue',
                  placeholder: 'Дата выдачи',
                  required: false,
                  type: 'text',
                  value: '',
                  mask: '',
                },
                {
                  name: 'passportFile',
                  placeholder: 'Сканированная копия документа',
                  required: false,
                  type: 'file',
                  value: '',
                  mask: '',
                },
                {
                  name: 'email',
                  placeholder: 'Адрес электронной почты',
                  required: true,
                  type: 'email',
                  value: '',
                  mask: '',
                },
                {
                  name: 'phone',
                  placeholder: 'Телефон',
                  required: true,
                  type: 'tel',
                  value: '',
                  mask: '+7 (999) 999-99-99',
                },
                {
                  name: 'address',
                  placeholder: 'Адрес места регистрации',
                  required: false,
                  type: 'text',
                  value: '',
                  mask: '',
                },
                {
                  name: 'actualAddress',
                  placeholder: 'Адрес места жительства',
                  required: false,
                  type: 'text',
                  value: '',
                  mask: '',
                },
              ],
            },
            {
              name: 'Вид просоединения',
              fields: [
                {
                  name: 'joiningType',
                  placeholder: 'Тип (схема) присоединения',
                  required: true,
                  type: 'radio',
                  value: '',
                  mask: '',
                  list: [
                    'Временное присоединениие',
                    'Присоединение по постоянно схеме',
                  ],
                },
                {
                  name: 'reason',
                  placeholder: 'Причина обращения',
                  required: false,
                  type: 'radio',
                  value: '',
                  mask: '',
                  list: [
                    'Новое обращение',
                    'Присоединение по постоянно схеме',
                    'Изменение схемы без пересмотра мощности',
                    'Увеличение присоединенной мощности',
                  ],
                },
              ],
            },
            {
              name: 'Энергопринимающие устройства',
              fields: [
                {
                  name: 'selectDevice',
                  placeholder: 'Выбрать наименование устройства',
                  required: false,
                  type: 'radio',
                  value: '',
                  mask: '',
                  list: [
                    'Административное/офисное здание',
                    'Базовая станция/оборудование сотовой связи',
                    'Гараж',
                    'Прочее',
                  ],
                },
                {
                  name: 'location',
                  placeholder: 'Местоположение',
                  required: false,
                  type: 'radio',
                  value: '',
                  mask: '',
                  list: [
                    'Городской',
                    'Сельский',
                  ],
                },
                {
                  name: 'cadastralNumber',
                  placeholder: 'Кадастровый номер земельного участка (помещения, здания)',
                  required: false,
                  type: 'text',
                  value: '',
                  mask: '',
                },
                {
                  name: 'deviceLocation',
                  placeholder: 'Местоположение устройства совпадает с',
                  required: false,
                  type: 'radio',
                  value: '',
                  mask: '',
                  list: [
                    'не совпадает ни с одним из адресов заявителя',
                    'адресом места регистрации',
                    'адресом местожительства',
                    'почтовым адресом',
                  ],
                },
                {
                  name: 'cadastralNumber',
                  placeholder: 'Субъект РФ',
                  required: false,
                  type: 'text',
                  value: '',
                  mask: '',
                },
                {
                  name: 'cadastralNumber',
                  placeholder: 'Район',
                  required: false,
                  type: 'text',
                  value: '',
                  mask: '',
                },
                {
                  name: 'cadastralNumber',
                  placeholder: 'Город',
                  required: false,
                  type: 'text',
                  value: '',
                  mask: '',
                },
                {
                  name: 'cadastralNumber',
                  placeholder: 'Населенный пункт',
                  required: false,
                  type: 'text',
                  value: '',
                  mask: '',
                },
                {
                  name: 'cadastralNumber',
                  placeholder: 'Улица',
                  required: false,
                  type: 'text',
                  value: '',
                  mask: '',
                },
                {
                  name: 'cadastralNumber',
                  placeholder: 'Номер дома или участка',
                  required: false,
                  type: 'text',
                  value: '',
                  mask: '',
                },
                {
                  name: 'cadastralNumber',
                  placeholder: 'Корпус',
                  required: false,
                  type: 'text',
                  value: '',
                  mask: '',
                },
                {
                  name: 'cadastralNumber',
                  placeholder: 'Строение',
                  required: false,
                  type: 'text',
                  value: '',
                  mask: '',
                },
                {
                  name: 'cadastralNumber',
                  placeholder: 'Квартира',
                  required: false,
                  type: 'text',
                  value: '',
                  mask: '',
                },
                {
                  name: 'cadastralNumber',
                  placeholder: 'Максмальная мощность устройства, кВТ',
                  required: false,
                  type: 'text',
                  value: '',
                  mask: '',
                },
                {
                  name: 'cadastralNumber',
                  placeholder: 'При напряжении',
                  required: false,
                  type: 'text',
                  value: '',
                  mask: '',
                },
                {
                  name: 'cadastralNumber',
                  placeholder: 'Максимальная мощность присоединяемых устройств',
                  required: false,
                  type: 'text',
                  value: '',
                  mask: '',
                },
                {
                  name: 'cadastralNumber',
                  placeholder: 'При напряжении',
                  required: false,
                  type: 'text',
                  value: '',
                  mask: '',
                },
                {
                  name: 'cadastralNumber',
                  placeholder: 'Характер нагрузки',
                  required: false,
                  type: 'text',
                  value: '',
                  mask: '',
                },
                {
                  name: 'deviceLocation',
                  placeholder: 'Категория надежности',
                  required: false,
                  type: 'radio',
                  value: '',
                  mask: '',
                  list: [
                    'III',
                    'II',
                    'I',
                    'II или III',
                  ],
                },
              ],
            },
            {
              name: 'Прочие',
              fields: [
                {
                  name: 'deviceLocation',
                  placeholder: 'Способ обмена документами',
                  required: false,
                  type: 'radio',
                  value: '',
                  mask: '',
                  list: [
                    'Электронное взаимодействие',
                    'Выдать лично',
                    'Направить почтой',
                  ],
                },
                {
                  name: 'deviceLocation',
                  placeholder: 'Способ уведомления при технологическом присоединении',
                  required: false,
                  type: 'radio',
                  value: '',
                  mask: '',
                  list: [
                    'sms',
                    'emal',
                    'телефон',
                  ],
                },
              ],
            },
            {
              name: 'Энергосбытовая организация',
              fields: [
                {
                  name: 'deviceLocation',
                  placeholder: 'Наименование ГП (ЭСО)',
                  required: false,
                  type: 'text',
                  value: '',
                  mask: '',
                },
                {
                  name: 'deviceLocation',
                  placeholder: 'Напишите свой вариант',
                  required: false,
                  type: 'text',
                  value: '',
                  mask: '',
                },
                {
                  name: 'deviceLocation',
                  placeholder: 'Вид договора',
                  required: false,
                  type: 'text',
                  value: '',
                  mask: '',
                },
                {
                  name: 'deviceLocation',
                  placeholder: 'Дата договора энергоснабжения (купли/продажи энергии)',
                  required: false,
                  type: 'text',
                  value: '',
                  mask: '',
                },
                {
                  name: 'deviceLocation',
                  placeholder: 'Номер договора',
                  required: false,
                  type: 'text',
                  value: '',
                  mask: '',
                },
                {
                  name: 'deviceLocation',
                  placeholder: 'Загрузить договор',
                  required: false,
                  type: 'file',
                  value: '',
                  mask: '',
                },
              ],
            },
            {
              name: 'Документы',
              fields: [
                {
                  name: 'deviceLocation',
                  placeholder: 'Осуществляется присоединение утройств, принадлежащих потребительскому кооперативу либо его членам',
                  required: false,
                  type: 'checkbox',
                  value: '',
                  mask: '',
                },
                {
                  name: 'deviceLocation',
                  placeholder: 'Осуществляется присоединение устройств на объекте/замельном участке, правоустнавливающие документы которого подразумевают долевую.совместную собственность',
                  required: false,
                  type: 'checkbox',
                  value: '',
                  mask: '',
                },
                {
                  name: 'deviceLocation',
                  placeholder: 'План расположения энергопринимающих устройств',
                  required: false,
                  type: 'file',
                  value: '',
                  mask: '',
                },
                {
                  name: 'deviceLocation',
                  placeholder: 'Документ, подтверждающий право собствености на объект или иное предусмотренное законом основание',
                  required: false,
                  type: 'file',
                  value: '',
                  mask: '',
                },
              ],
            },
          ],
        },
        {
          type: 'Юридическое лицо',
          sections: [
            {
              name: 'Заявитель',
              fields: [
                {
                  name: 'typeUser',
                  placeholder: 'Тип заявителя',
                  required: true,
                  type: 'text',
                  value: '',
                  mask: '',
                },
                {
                  name: 'surname',
                  placeholder: 'Фамилия руководителя',
                  required: true,
                  type: 'text',
                  value: '',
                  mask: '',
                },
                {
                  name: 'name',
                  placeholder: 'Имя руководителя',
                  required: true,
                  type: 'text',
                  value: '',
                  mask: '',
                },
                {
                  name: 'middleName',
                  placeholder: 'Отчество руководителя',
                  required: false,
                  type: 'text',
                  value: '',
                  mask: '',
                },
                {
                  name: 'inn',
                  placeholder: 'ИНН',
                  required: false,
                  type: 'text',
                  value: '',
                  mask: '',
                },
                {
                  name: 'legalForm',
                  placeholder: 'Организационно-правовая форма',
                  required: false,
                  type: 'text',
                  value: '',
                  mask: '',
                },
                {
                  name: 'email',
                  placeholder: 'Адрес электронной почты',
                  required: true,
                  type: 'email',
                  value: '',
                  mask: '',
                },
                {
                  name: 'phone',
                  placeholder: 'Телефон',
                  required: true,
                  type: 'tel',
                  value: '',
                  mask: '+7 (999) 999-99-99',
                },
                {
                  name: 'address',
                  placeholder: 'Юридический адрес',
                  required: false,
                  type: 'text',
                  value: '',
                  mask: '',
                },
                {
                  name: 'postalAddress',
                  placeholder: 'Почтовый адрес',
                  required: false,
                  type: 'text',
                  value: '',
                  mask: '',
                },
                {
                  name: 'actualAddress',
                  placeholder: 'Фактический адрес',
                  required: false,
                  type: 'text',
                  value: '',
                  mask: '',
                },
              ],
            },
            {
              name: 'Вид просоединения',
              fields: [
                {
                  name: 'joiningType',
                  placeholder: 'Тип (схема) присоединения',
                  required: true,
                  type: 'radio',
                  value: '',
                  mask: '',
                  list: [
                    'Временное присоединениие',
                    'Присоединение по постоянно схеме',
                  ],
                },
                {
                  name: 'reason',
                  placeholder: 'Причина обращения',
                  required: false,
                  type: 'radio',
                  value: '',
                  mask: '',
                  list: [
                    'Новое обращение',
                    'Присоединение по постоянно схеме',
                    'Изменение схемы без пересмотра мощности',
                    'Увеличение присоединенной мощности',
                  ],
                },
              ],
            },
            {
              name: 'Энергопринимающие устройства',
              fields: [
                {
                  name: 'selectDevice',
                  placeholder: 'Выбрать наименование устройства',
                  required: false,
                  type: 'radio',
                  value: '',
                  mask: '',
                  list: [
                    'Административное/офисное здание',
                    'Базовая станция/оборудование сотовой связи',
                    'Гараж',
                    'Прочее',
                  ],
                },
                {
                  name: 'location',
                  placeholder: 'Местоположение',
                  required: false,
                  type: 'radio',
                  value: '',
                  mask: '',
                  list: [
                    'Городской',
                    'Сельский',
                  ],
                },
                {
                  name: 'cadastralNumber',
                  placeholder: 'Кадастровый номер земельного участка (помещения, здания)',
                  required: false,
                  type: 'text',
                  value: '',
                  mask: '',
                },
                {
                  name: 'deviceLocation',
                  placeholder: 'Местоположение устройства совпадает с',
                  required: false,
                  type: 'radio',
                  value: '',
                  mask: '',
                  list: [
                    'не совпадает ни с одним из адресов заявителя',
                    'адресом места регистрации',
                    'адресом местожительства',
                    'почтовым адресом',
                  ],
                },
                {
                  name: 'cadastralNumber',
                  placeholder: 'Субъект РФ',
                  required: false,
                  type: 'text',
                  value: '',
                  mask: '',
                },
                {
                  name: 'cadastralNumber',
                  placeholder: 'Район',
                  required: false,
                  type: 'text',
                  value: '',
                  mask: '',
                },
                {
                  name: 'cadastralNumber',
                  placeholder: 'Город',
                  required: false,
                  type: 'text',
                  value: '',
                  mask: '',
                },
                {
                  name: 'cadastralNumber',
                  placeholder: 'Населенный пункт',
                  required: false,
                  type: 'text',
                  value: '',
                  mask: '',
                },
                {
                  name: 'cadastralNumber',
                  placeholder: 'Улица',
                  required: false,
                  type: 'text',
                  value: '',
                  mask: '',
                },
                {
                  name: 'cadastralNumber',
                  placeholder: 'Номер дома или участка',
                  required: false,
                  type: 'text',
                  value: '',
                  mask: '',
                },
                {
                  name: 'cadastralNumber',
                  placeholder: 'Корпус',
                  required: false,
                  type: 'text',
                  value: '',
                  mask: '',
                },
                {
                  name: 'cadastralNumber',
                  placeholder: 'Строение',
                  required: false,
                  type: 'text',
                  value: '',
                  mask: '',
                },
                {
                  name: 'cadastralNumber',
                  placeholder: 'Квартира',
                  required: false,
                  type: 'text',
                  value: '',
                  mask: '',
                },
                {
                  name: 'cadastralNumber',
                  placeholder: 'Максмальная мощность устройства, кВТ',
                  required: false,
                  type: 'text',
                  value: '',
                  mask: '',
                },
                {
                  name: 'cadastralNumber',
                  placeholder: 'При напряжении',
                  required: false,
                  type: 'text',
                  value: '',
                  mask: '',
                },
                {
                  name: 'cadastralNumber',
                  placeholder: 'Максимальная мощность присоединяемых устройств',
                  required: false,
                  type: 'text',
                  value: '',
                  mask: '',
                },
                {
                  name: 'cadastralNumber',
                  placeholder: 'При напряжении',
                  required: false,
                  type: 'text',
                  value: '',
                  mask: '',
                },
                {
                  name: 'cadastralNumber',
                  placeholder: 'Характер нагрузки',
                  required: false,
                  type: 'text',
                  value: '',
                  mask: '',
                },
                {
                  name: 'deviceLocation',
                  placeholder: 'Категория надежности',
                  required: false,
                  type: 'radio',
                  value: '',
                  mask: '',
                  list: [
                    'III',
                    'II',
                    'I',
                    'II или III',
                  ],
                },
              ],
            },
            {
              name: 'Прочие',
              fields: [
                {
                  name: 'deviceLocation',
                  placeholder: 'Способ обмена документами',
                  required: false,
                  type: 'radio',
                  value: '',
                  mask: '',
                  list: [
                    'Электронное взаимодействие',
                    'Выдать лично',
                    'Направить почтой',
                  ],
                },
                {
                  name: 'deviceLocation',
                  placeholder: 'Способ уведомления при технологическом присоединении',
                  required: false,
                  type: 'radio',
                  value: '',
                  mask: '',
                  list: [
                    'sms',
                    'emal',
                    'телефон',
                  ],
                },
              ],
            },
            {
              name: 'Энергосбытовая организация',
              fields: [
                {
                  name: 'deviceLocation',
                  placeholder: 'Наименование ГП (ЭСО)',
                  required: false,
                  type: 'text',
                  value: '',
                  mask: '',
                },
                {
                  name: 'deviceLocation',
                  placeholder: 'Напишите свой вариант',
                  required: false,
                  type: 'text',
                  value: '',
                  mask: '',
                },
                {
                  name: 'deviceLocation',
                  placeholder: 'Вид договора',
                  required: false,
                  type: 'text',
                  value: '',
                  mask: '',
                },
                {
                  name: 'deviceLocation',
                  placeholder: 'Дата договора энергоснабжения (купли/продажи энергии)',
                  required: false,
                  type: 'text',
                  value: '',
                  mask: '',
                },
                {
                  name: 'deviceLocation',
                  placeholder: 'Номер договора',
                  required: false,
                  type: 'text',
                  value: '',
                  mask: '',
                },
                {
                  name: 'deviceLocation',
                  placeholder: 'Загрузить договор',
                  required: false,
                  type: 'file',
                  value: '',
                  mask: '',
                },
              ],
            },
            {
              name: 'Документы',
              fields: [
                {
                  name: 'deviceLocation',
                  placeholder: 'Осуществляется присоединение утройств, принадлежащих потребительскому кооперативу либо его членам',
                  required: false,
                  type: 'checkbox',
                  value: '',
                  mask: '',
                },
                {
                  name: 'deviceLocation',
                  placeholder: 'Осуществляется присоединение устройств на объекте/замельном участке, правоустнавливающие документы которого подразумевают долевую.совместную собственность',
                  required: false,
                  type: 'checkbox',
                  value: '',
                  mask: '',
                },
                {
                  name: 'deviceLocation',
                  placeholder: 'План расположения энергопринимающих устройств',
                  required: false,
                  type: 'file',
                  value: '',
                  mask: '',
                },
                {
                  name: 'deviceLocation',
                  placeholder: 'Документ, подтверждающий право собствености на объект или иное предусмотренное законом основание',
                  required: false,
                  type: 'file',
                  value: '',
                  mask: '',
                },
              ],
            },
          ],
        },
        {
          type: 'Индивидуальный предприниматель',
          sections: [
            {
              name: 'Заявитель',
              fields: [
                {
                  name: 'typeUser',
                  placeholder: 'Тип заявителя',
                  required: true,
                  type: 'text',
                  value: '',
                  mask: '',
                },
                {
                  name: 'surname',
                  placeholder: 'Фамилия',
                  required: true,
                  type: 'text',
                  value: '',
                  mask: '',
                },
                {
                  name: 'name',
                  placeholder: 'Имя',
                  required: true,
                  type: 'text',
                  value: '',
                  mask: '',
                },
                {
                  name: 'middleName',
                  placeholder: 'Отчество',
                  required: false,
                  type: 'text',
                  value: '',
                  mask: '',
                },
                {
                  name: 'inn',
                  placeholder: 'ИНН',
                  required: false,
                  type: 'text',
                  value: '',
                  mask: '',
                },
                {
                  name: 'passport',
                  placeholder: 'Паспорт',
                  required: false,
                  type: 'text',
                  value: '',
                  mask: '',
                },
                {
                  name: 'series',
                  placeholder: 'Серия',
                  required: false,
                  type: 'text',
                  value: '',
                  mask: '',
                },
                {
                  name: 'number',
                  placeholder: 'Номер',
                  required: false,
                  type: 'text',
                  value: '',
                  mask: '',
                },
                {
                  name: 'issued',
                  placeholder: 'Выдан',
                  required: false,
                  type: 'text',
                  value: '',
                  mask: '',
                },
                {
                  name: 'dateIssue',
                  placeholder: 'Дата выдачи',
                  required: false,
                  type: 'text',
                  value: '',
                  mask: '',
                },
                {
                  name: 'passportFile',
                  placeholder: 'Сканированная копия документа',
                  required: false,
                  type: 'file',
                  value: '',
                  mask: '',
                },
                {
                  name: 'email',
                  placeholder: 'Адрес электронной почты',
                  required: true,
                  type: 'email',
                  value: '',
                  mask: '',
                },
                {
                  name: 'phone',
                  placeholder: 'Телефон',
                  required: true,
                  type: 'tel',
                  value: '',
                  mask: '+7 (999) 999-99-99',
                },
                {
                  name: 'address',
                  placeholder: 'Адрес места регистрации',
                  required: false,
                  type: 'text',
                  value: '',
                  mask: '',
                },
                {
                  name: 'postalAddress',
                  placeholder: 'Почтовый адрес',
                  required: false,
                  type: 'text',
                  value: '',
                  mask: '',
                },
                {
                  name: 'actualAddress',
                  placeholder: 'Адрес места жительства',
                  required: false,
                  type: 'text',
                  value: '',
                  mask: '',
                },
              ],
            },
            {
              name: 'Вид просоединения',
              fields: [
                {
                  name: 'joiningType',
                  placeholder: 'Тип (схема) присоединения',
                  required: true,
                  type: 'radio',
                  value: '',
                  mask: '',
                  list: [
                    'Временное присоединениие',
                    'Присоединение по постоянно схеме',
                  ],
                },
                {
                  name: 'reason',
                  placeholder: 'Причина обращения',
                  required: false,
                  type: 'radio',
                  value: '',
                  mask: '',
                  list: [
                    'Новое обращение',
                    'Присоединение по постоянно схеме',
                    'Изменение схемы без пересмотра мощности',
                    'Увеличение присоединенной мощности',
                  ],
                },
              ],
            },
            {
              name: 'Энергопринимающие устройства',
              fields: [
                {
                  name: 'selectDevice',
                  placeholder: 'Выбрать наименование устройства',
                  required: false,
                  type: 'radio',
                  value: '',
                  mask: '',
                  list: [
                    'Административное/офисное здание',
                    'Базовая станция/оборудование сотовой связи',
                    'Гараж',
                    'Прочее',
                  ],
                },
                {
                  name: 'location',
                  placeholder: 'Местоположение',
                  required: false,
                  type: 'radio',
                  value: '',
                  mask: '',
                  list: [
                    'Городской',
                    'Сельский',
                  ],
                },
                {
                  name: 'cadastralNumber',
                  placeholder: 'Кадастровый номер земельного участка (помещения, здания)',
                  required: false,
                  type: 'text',
                  value: '',
                  mask: '',
                },
                {
                  name: 'deviceLocation',
                  placeholder: 'Местоположение устройства совпадает с',
                  required: false,
                  type: 'radio',
                  value: '',
                  mask: '',
                  list: [
                    'не совпадает ни с одним из адресов заявителя',
                    'адресом места регистрации',
                    'адресом местожительства',
                    'почтовым адресом',
                  ],
                },
                {
                  name: 'cadastralNumber',
                  placeholder: 'Субъект РФ',
                  required: false,
                  type: 'text',
                  value: '',
                  mask: '',
                },
                {
                  name: 'cadastralNumber',
                  placeholder: 'Район',
                  required: false,
                  type: 'text',
                  value: '',
                  mask: '',
                },
                {
                  name: 'cadastralNumber',
                  placeholder: 'Город',
                  required: false,
                  type: 'text',
                  value: '',
                  mask: '',
                },
                {
                  name: 'cadastralNumber',
                  placeholder: 'Населенный пункт',
                  required: false,
                  type: 'text',
                  value: '',
                  mask: '',
                },
                {
                  name: 'cadastralNumber',
                  placeholder: 'Улица',
                  required: false,
                  type: 'text',
                  value: '',
                  mask: '',
                },
                {
                  name: 'cadastralNumber',
                  placeholder: 'Номер дома или участка',
                  required: false,
                  type: 'text',
                  value: '',
                  mask: '',
                },
                {
                  name: 'cadastralNumber',
                  placeholder: 'Корпус',
                  required: false,
                  type: 'text',
                  value: '',
                  mask: '',
                },
                {
                  name: 'cadastralNumber',
                  placeholder: 'Строение',
                  required: false,
                  type: 'text',
                  value: '',
                  mask: '',
                },
                {
                  name: 'cadastralNumber',
                  placeholder: 'Квартира',
                  required: false,
                  type: 'text',
                  value: '',
                  mask: '',
                },
                {
                  name: 'cadastralNumber',
                  placeholder: 'Максмальная мощность устройства, кВТ',
                  required: false,
                  type: 'text',
                  value: '',
                  mask: '',
                },
                {
                  name: 'cadastralNumber',
                  placeholder: 'При напряжении',
                  required: false,
                  type: 'text',
                  value: '',
                  mask: '',
                },
                {
                  name: 'cadastralNumber',
                  placeholder: 'Максимальная мощность присоединяемых устройств',
                  required: false,
                  type: 'text',
                  value: '',
                  mask: '',
                },
                {
                  name: 'cadastralNumber',
                  placeholder: 'При напряжении',
                  required: false,
                  type: 'text',
                  value: '',
                  mask: '',
                },
                {
                  name: 'cadastralNumber',
                  placeholder: 'Характер нагрузки',
                  required: false,
                  type: 'text',
                  value: '',
                  mask: '',
                },
                {
                  name: 'deviceLocation',
                  placeholder: 'Категория надежности',
                  required: false,
                  type: 'radio',
                  value: '',
                  mask: '',
                  list: [
                    'III',
                    'II',
                    'I',
                    'II или III',
                  ],
                },
              ],
            },
            {
              name: 'Прочие',
              fields: [
                {
                  name: 'deviceLocation',
                  placeholder: 'Способ обмена документами',
                  required: false,
                  type: 'radio',
                  value: '',
                  mask: '',
                  list: [
                    'Электронное взаимодействие',
                    'Выдать лично',
                    'Направить почтой',
                  ],
                },
                {
                  name: 'deviceLocation',
                  placeholder: 'Способ уведомления при технологическом присоединении',
                  required: false,
                  type: 'radio',
                  value: '',
                  mask: '',
                  list: [
                    'sms',
                    'emal',
                    'телефон',
                  ],
                },
              ],
            },
            {
              name: 'Энергосбытовая организация',
              fields: [
                {
                  name: 'deviceLocation',
                  placeholder: 'Наименование ГП (ЭСО)',
                  required: false,
                  type: 'text',
                  value: '',
                  mask: '',
                },
                {
                  name: 'deviceLocation',
                  placeholder: 'Напишите свой вариант',
                  required: false,
                  type: 'text',
                  value: '',
                  mask: '',
                },
                {
                  name: 'deviceLocation',
                  placeholder: 'Вид договора',
                  required: false,
                  type: 'text',
                  value: '',
                  mask: '',
                },
                {
                  name: 'deviceLocation',
                  placeholder: 'Дата договора энергоснабжения (купли/продажи энергии)',
                  required: false,
                  type: 'text',
                  value: '',
                  mask: '',
                },
                {
                  name: 'deviceLocation',
                  placeholder: 'Номер договора',
                  required: false,
                  type: 'text',
                  value: '',
                  mask: '',
                },
                {
                  name: 'deviceLocation',
                  placeholder: 'Загрузить договор',
                  required: false,
                  type: 'file',
                  value: '',
                  mask: '',
                },
              ],
            },
            {
              name: 'Документы',
              fields: [
                {
                  name: 'deviceLocation',
                  placeholder: 'Осуществляется присоединение утройств, принадлежащих потребительскому кооперативу либо его членам',
                  required: false,
                  type: 'checkbox',
                  value: '',
                  mask: '',
                },
                {
                  name: 'deviceLocation',
                  placeholder: 'Осуществляется присоединение устройств на объекте/замельном участке, правоустнавливающие документы которого подразумевают долевую.совместную собственность',
                  required: false,
                  type: 'checkbox',
                  value: '',
                  mask: '',
                },
                {
                  name: 'deviceLocation',
                  placeholder: 'План расположения энергопринимающих устройств',
                  required: false,
                  type: 'file',
                  value: '',
                  mask: '',
                },
                {
                  name: 'deviceLocation',
                  placeholder: 'Документ, подтверждающий право собствености на объект или иное предусмотренное законом основание',
                  required: false,
                  type: 'file',
                  value: '',
                  mask: '',
                },
              ],
            },
          ],
        },
      ],
    };
  },
  computed: {
    typeList() {
      return this.dataList.map((item) => item.type);
    },
    sectionList() {
      const type = this.dataList.find((item) => item.type === this.typeSelect);
      return type.sections.map((item) => item.name);
    },
    fieldsList() {
      const type = this.dataList.find((item) => item.type === this.typeSelect);
      const section = type.sections.find((item) => item.name === this.sectionSelect);
      return section.fields;
    },
    nextSection() {
      const selectIndex = this.sectionList.findIndex((item) => item === this.sectionSelect);
      return this.sectionList[selectIndex + 1] ? this.sectionList[selectIndex + 1] : false;
    },
  },
  methods: {
    getUserInfo() {
      this.typeSelect = 'Физическое лицо';
    },
    resetSectionSelect() {
      this.sectionSelect = 'Заявитель';
    },
    changeSection() {
      if (this.nextSection) {
        this.sectionSelect = this.nextSection;
      }
    },
  },
  created() {
    this.getUserInfo();
  },
};
</script>
